version: '3.9'

services:
  frontend:
    build:
      context: ./fe
      args:
        REACT_APP_API_URL: http://localhost
    ports:
      - "80:80"  
    volumes:
      - ./fe:/app-fe

  db:
    container_name: mysql-container
    image: mysql:8.0
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: mydb

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

  web:
    build: ./be
    ports:
      - "8000:8000" 
    volumes:
      - ./be:/app-be
    environment:
      MODE: "PROD"
    depends_on:
      - db

